apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-service
  template:
    metadata:
      labels:
        app: recipe-service
    spec:
      containers:
      - name: recipe-service
        image:  peytonpeaceful/recipe-service:latest # Change to your DockerHub image if needed
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://dpg-d4e76p8gjchc73fbd6dg-a.oregon-postgres.render.com:5432/user_service_baoy"
        - name: SPRING_DATASOURCE_USERNAME
          value: "user_service_baoy_user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "swOLtPmLusWZVCt5laf6mesnherBcNuZ"