apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-service
  template:
    metadata:
      labels:
        app: recipe-service
    spec:
      containers:
        - name: recipe-service
          image: sachittarway/recipe-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
            - containerPort: 9090  # gRPC port
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: GRPC_SERVER_PORT
              value: "9090"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-recipe-service:5432/recipe_service_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "notification-group"
            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: "earliest"
            - name: SPRING_KAFKA_PRODUCER_ACKS
              value: "all"
            - name: SPRING_KAFKA_PROPERTIES_BOOTSTRAP_SERVERS
              value: "kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: SPRING_KAFKA_ADMIN_PROPERTIES_BOOTSTRAP_SERVERS
              value: "kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: USER_SERVICE_URL
              value: "http://user-service:8081/api/v1/users/"
            - name: GL_API_KEY
              value: "*********************************" # Replace with actual API key
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-service
spec:
  selector:
    app: recipe-service
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
